image: node:18

stages:
  - build
  - test
  - deploy

cache:
  paths:
    - backend/node_modules/

before_script:
  - cd backend

install_dependencies-job:
  stage: build
  script:
    - npm install

lint-job:
  stage: test
  script:
    - npm run lint

test-job:
  stage: test
  script:
    - npm run test

deploy-job:
  stage: deploy
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
