image: node:18

cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - ${BACKEND_DIR}/node_modules/
    - ${FRONTEND_DIR}/node_modules/
    - ${FRONTEND_DIR}/.nuxt/ # Кешуємо директорію .nuxt

stages:
  - build
  - lint
  - test

variables:
  BACKEND_DIR: "backend"
  FRONTEND_DIR: "frontend"

.build: &build
  script:
    - cd $CI_PROJECT_DIR/$APP_DIR
    - npm install --prefer-offline
    - npm run build

.lint: &lint
  script:
    - cd $CI_PROJECT_DIR/$APP_DIR
    - npm run lint

.test: &test
  script:
    - cd $CI_PROJECT_DIR/$APP_DIR
    - npm run test

backend_build:
  stage: build
  variables:
    APP_DIR: ${BACKEND_DIR}
  <<: *build

frontend_build:
  stage: build
  variables:
    APP_DIR: ${FRONTEND_DIR}
  <<: *build

backend_lint:
  stage: lint
  needs: ["backend_build"]
  variables:
    APP_DIR: ${BACKEND_DIR}
  <<: *lint

frontend_lint:
  stage: lint
  needs: ["frontend_build"]
  variables:
    APP_DIR: ${FRONTEND_DIR}
  <<: *lint

backend_test:
  stage: test
  needs: ["backend_build"]
  variables:
    APP_DIR: ${BACKEND_DIR}
  <<: *test

backend_test_e2e:
  stage: test
  needs: ["backend_build"]
  variables:
    APP_DIR: ${BACKEND_DIR}
  script:
    - cd $CI_PROJECT_DIR/$APP_DIR
    - npm run test:e2e

frontend_test:
  stage: test
  needs: ["frontend_build"]
  variables:
    APP_DIR: ${FRONTEND_DIR}
  needs: ["frontend_build"]
  <<: *test
