version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16 # Замініть на потрібну версію Node.js
    commands:
      - ls -a
      - cd backend
      - ls -a
      - npm install
  build:
    commands:
      - ls -a
      - cd ./backend
      - npm run build # Або іншу команду для збирання вашого NestJS застосунку
  post_build:
    commands:
      - ls -a
      - cd backend
      - mv dist ../ # Перемістіть збірку бекенду в корінь для розгортання на Beanstalk

artifacts:
  files:
    - "**/*"
  base-directory: "." # Вкажіть кореневу директорію для артефактів
